apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: go-hello
  name: go-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-hello
  template:
    metadata:
      labels:
        run: go-hello
    spec:
      containers:
      - image: asoykan/go-hello
        imagePullPolicy: IfNotPresent
        name: go-hello
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: go-hello
spec:
  selector:
    run: go-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80